POST http://localhost:4000/thread/ck5au4dez0000jvfwkzk4pgsi
Content-Type: application/json

{
    "content": "zzzzzzzzzzzzz"
}

###

POST http://localhost:4000/thread
Content-Type: application/json

{
    "content": "azxczxcxzc"
}

###

GET http://localhost:4000/thread/ck5au4dez0000jvfwkzk4pgsi
